### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by cjmwid** [MyBBService/Ticketsystem#4]
Parse error: syntax error, unexpected T_OBJECT_OPERATOR in /home/alliance/public_html/forums/inc/plugins/jones/core/Installer/Alerts.php on line 19

Happens when i press the install button.

**Comment by JN-Jones** [comment]
PHP 5.2 isn't supported, the error sounds like you're using it.

**Comment by cjmwid** [comment]
Negative. PHP 5.3.10

Link to php info
http://alliancegamerz.net/phpinfo.php

**Comment by JN-Jones** [comment]
Unfortunately I don't have a 5.3 test installation - can you send me ftp details and an admin account on the community forums? I'll fix the issue then.

**Comment by cjmwid** [comment]
I have sent you the email with all the information you need to admin@jonesboard.de

**Comment by JN-Jones** [comment]
Fixed with https://github.com/MyBBService/Ticketsystem/commit/024839e3ea209910f80759b06d88b0f14a2d4ff8 and https://github.com/JN-Jones/JonesCore/commit/4ac212391d9186410d82d464a671423f351d69bd
Note that you need to download the Ticketsystem from GitHub. JonesCore should be updated automatically

**Comment by cjmwid** [comment]
Thankyou good sir.  If u would like i can leave that up for you and when mybb updates I can update that one also so u will have a pop 5.3 testing place.

**Comment by JN-Jones** [comment]
No need for it - it's mainly one thing I always write that throws an error with PHP 5.3. I'll try to remember it when updating the other plugins :P
